// services/blobatar/packages/preact/src/index.tsx
/**
 * `@blobatar/preact` — the Preact adapter.
 *
 * Written in JSX and compiled against `preact/jsx-runtime`, which is what
 * `tsconfig.json`'s `jsxImportSource` selects and `scripts/build.ts` keeps
 * external. That is the build isolation ADR-0009 split the packages for: core's
 * single `Bun.build` could not hold Preact's runtime beside React's transform,
 * and the attempt that tried gave up and returned a raw DOM node from a
 * function component — which Preact drops silently for an empty string, with a
 * clean typecheck and a green suite.
 *
 * `packages/harness` renders this package with `preact-render-to-string` for
 * exactly that reason. An adapter is only known to work when something has
 * watched it produce markup.
 */

import { useMemo } from "preact/hooks";
import type { JSX } from "preact";
import { _parts, type Animate, type BlobatarOptions } from "blobatar/internal";
import { blobatarUri } from "blobatar/uri";

/**
 * Two rendering modes, and the props follow the mode — the same union core's
 * React component declares, for the same reason. `onLoad` should stop
 * type-checking the moment animation is on, because it stops firing.
 */
type StaticProps = { animate?: false } & Omit<
  JSX.HTMLAttributes<HTMLImageElement>,
  "src"
>;

type AnimatedProps = { animate: Animate } & Omit<
  JSX.SVGAttributes<SVGSVGElement>,
  "children" | "dangerouslySetInnerHTML"
>;

export type BlobatarProps = {
  /**
   * Who the blobatar is for. A username, a display name, an email, a bot's
   * handle, a user id — any string, and the same string always renders the
   * same blobatar. The only required prop.
   */
  name: string;
} & BlobatarOptions &
  (StaticProps | AnimatedProps);

export function Blobatar({
  name: seed,
  size,
  background,
  palette,
  hue,
  tone,
  normalize,
  contrast,
  title,
  animate,
  expression,
  traits,
  ...rest
}: BlobatarProps) {
  // Pulled out explicitly like every other option, because what is left in
  // `rest` goes straight onto the DOM element — a `traits` object spread onto
  // an `<img>` is a malformed attribute per blobatar.
  const opts = {
    size,
    background,
    palette,
    hue,
    tone,
    normalize,
    contrast,
    title,
    expression,
    traits,
  };

  // Both branches are hooks-stable: `animate` changing swaps the element type,
  // which remounts anyway.
  const dep = JSON.stringify([seed, opts, animate]);

  const src = useMemo(() => (animate ? "" : blobatarUri(seed, opts)), [dep]);

  const parts = useMemo(
    () => (animate ? _parts(seed, { ...opts, animate }) : null),
    [dep],
  );

  /**
   * The markup object, kept stable by identity and not just by value.
   *
   * Preact diffs `dangerouslySetInnerHTML` by comparing `__html` against the
   * previous vnode's, so a fresh `{__html}` literal carrying the same string is
   * cheap here in a way it is not in React. Memoized anyway, and deliberately:
   * the two adapters are read side by side, the cost is one comparison, and the
   * reason the root `<g>` is a real element rather than part of this string is
   * the same in both — see below.
   */
  const html = useMemo(() => ({ __html: parts?.inner ?? "" }), [parts?.inner]);

  if (parts) {
    const { style, ...svgRest } = rest as JSX.SVGAttributes<SVGSVGElement>;
    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 100 100"
        width={size}
        height={size}
        // With a `title` the markup carries a `<title>`, so this is a labelled
        // image; without one it is decoration and should be skipped entirely —
        // the same call `alt=""` makes on the `<img>` path. Never both: a
        // `role="img"` that is also `aria-hidden` just contradicts itself.
        role={title ? "img" : undefined}
        aria-hidden={title ? undefined : true}
        style={{
          ...(parts.vars as JSX.CSSProperties),
          ...(style as JSX.CSSProperties),
        }}
        {...svgRest}
      >
        {/*
          Three real children rather than one innerHTML blob, and the reason is
          the morph. Only the third varies at runtime — its class does, when the
          expression changes — and `dangerouslySetInnerHTML` is all-or-nothing:
          had the root `<g>` stayed inside that string, every expression change
          would replace the entire subtree. A fresh element has no previous
          computed value, so no transition runs on it and every idle animation
          under it restarts from phase zero.

          The first two have to be siblings of the root rather than inside it:
          `<title>` names the element it is the first child of, so nesting it
          would label a `<g>` instead of this `<svg>`, and the backdrop must sit
          outside the hover-lift or the plate scales with the creature.
        */}
        {title ? <title>{title}</title> : null}
        {parts.bg ? <path d={parts.bg.d} fill={parts.bg.fill} /> : null}
        <g class={parts.cls} dangerouslySetInnerHTML={html} />
      </svg>
    );
  }

  const { alt, ...imgRest } = rest as JSX.HTMLAttributes<HTMLImageElement> & {
    alt?: string;
  };
  return (
    <img src={src} width={size} height={size} alt={alt ?? title ?? ""} {...imgRest} />
  );
}

// services/blobatar/packages/solid/src/index.tsx
/**
 * `@blobatar/solid` — the Solid adapter.
 *
 * Written in Solid JSX and compiled by `babel-preset-solid`, which is the
 * thing ADR-0009 split the packages to make possible. An earlier attempt at
 * three adapters as subpaths of core could not hold five mutually
 * incompatible JSX transforms in one `Bun.build` call, gave up, and hand-rolled
 * `document.createElementNS` instead — shipping a Preact adapter that rendered
 * an empty string. Build isolation is what this package spends its existence
 * on; `scripts/build.ts` is where it collects it.
 *
 * So: no DOM construction here. Anything written against `document` renders
 * nowhere there is no `document`, which is every SSR consumer and the harness
 * row that would have caught the empty string.
 */

import { createMemo, splitProps, type JSX } from "solid-js";
import { _parts, type Animate, type BlobatarOptions } from "blobatar/internal";
import { blobatarUri } from "blobatar/uri";

/**
 * Two rendering modes, and the props follow the mode — the same union core's
 * React component declares, for the same reason. `onLoad` should stop
 * type-checking the moment animation is on, because it stops firing.
 */
type StaticProps = { animate?: false } & Omit<
  JSX.ImgHTMLAttributes<HTMLImageElement>,
  "src"
>;

type AnimatedProps = { animate: Animate } & Omit<
  JSX.SvgSVGAttributes<SVGSVGElement>,
  "children" | "innerHTML" | "viewBox"
>;

export type BlobatarProps = {
  /**
   * Who the blobatar is for. A username, a display name, an email, a bot's
   * handle, a user id — any string, and the same string always renders the
   * same blobatar. The only required prop.
   */
  name: string;
} & BlobatarOptions &
  (StaticProps | AnimatedProps);

/**
 * Split by name rather than destructured, and this is not stylistic.
 *
 * Destructuring a Solid component's props reads every one of them once, at
 * setup, and drops the getters that make them reactive — a blobatar written
 * that way renders the first `name` it is given and then never changes again.
 * `splitProps` is the same separation done without the read.
 *
 * The list is also what keeps options off the DOM: whatever is left in `rest`
 * is spread onto the element, and a `traits` object on an `<img>` is a
 * malformed attribute per blobatar.
 */
const OPTIONS = [
  "name",
  "size",
  "background",
  "palette",
  "hue",
  "tone",
  "normalize",
  "contrast",
  "title",
  "animate",
  "expression",
  "traits",
] as const;

export function Blobatar(props: BlobatarProps) {
  const [own, rest] = splitProps(props as BlobatarProps & Record<string, unknown>, OPTIONS);

  const opts = createMemo<BlobatarOptions>(() => ({
    size: own.size,
    background: own.background,
    palette: own.palette,
    hue: own.hue,
    tone: own.tone,
    normalize: own.normalize,
    contrast: own.contrast,
    title: own.title,
    expression: own.expression,
    traits: own.traits,
  }));

  const parts = createMemo(() =>
    own.animate ? _parts(own.name, { ...opts(), animate: own.animate }) : null,
  );

  const src = createMemo(() => (own.animate ? "" : blobatarUri(own.name, opts())));

  return (
    <>
      {(() => {
        const p = parts();
        if (p) {
          const [carried, svgRest] = splitProps(rest, ["style"]);
          return (
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 100 100"
              width={own.size}
              height={own.size}
              // With a `title` the markup carries a `<title>`, so this is a
              // labelled image; without one it is decoration and should be
              // skipped entirely — the same call `alt=""` makes on the `<img>`
              // path. Never both.
              role={own.title ? "img" : undefined}
              aria-hidden={own.title ? undefined : true}
              style={{
                ...(p.vars as JSX.CSSProperties),
                ...(carried.style as JSX.CSSProperties),
              }}
              {...(svgRest as JSX.SvgSVGAttributes<SVGSVGElement>)}
            >
              {/*
                Three real children rather than one `innerHTML` blob, and the
                reason is the morph. Only the third varies at runtime — its
                class does, when the expression changes — and setting
                `innerHTML` is all-or-nothing: had the root `<g>` stayed inside
                that string, every expression change would replace the whole
                subtree, and a fresh element has no previous computed value, so
                no transition runs on it and every idle animation under it
                restarts from phase zero.

                The first two are siblings of the root rather than inside it:
                `<title>` names the element it is the first child of, and the
                backdrop must sit outside the hover-lift or the plate scales
                with the creature.
              */}
              {own.title ? <title>{own.title}</title> : null}
              {p.bg ? <path d={p.bg.d} fill={p.bg.fill} /> : null}
              <g class={p.cls} innerHTML={p.inner} />
            </svg>
          );
        }

        const [carried, imgRest] = splitProps(rest, ["alt"]);
        return (
          <img
            src={src()}
            width={own.size}
            height={own.size}
            alt={(carried.alt as string | undefined) ?? own.title ?? ""}
            {...(imgRest as JSX.ImgHTMLAttributes<HTMLImageElement>)}
          />
        );
      })()}
    </>
  );
}
